docker-compose-yaml: docker-compose.yml

environments:
  main:
    routes:
      - nginx:
        - dev.proworkers.com:
            tls-acme: false
        - staging.proworkers.com:
            tls-acme: false
        - partners.amazee.io:
            tls-acme: false
