version: '2.3'

x-lagoon-project:
  # Lagoon project name (leave `&lagoon-project` when you edit this)
  &lagoon-project redirector-example

x-environment:
  &default-environment
    LAGOON_PROJECT: *lagoon-project
    # Route that should be used locally
    LAGOON_ROUTE: https://redirector-example.docker.amazee.io

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CLI_IMAGE: *lagoon-project # Inject the name of the cli image
    labels:
      lagoon.type: nginx
      LAGOON_LOCALDEV_URL: nginx-redirector.com.docker.amazee.io # generate another route for nginx, by default we go to varnish
    networks:
      - amazeeio-network
      - default


networks:
  amazeeio-network:
    external: true
